services:
  postgresql-reviewer-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgresql-reviewer-frontend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NUXT_PUBLIC_API_BASE_URL=${API_BASE_URL:-http://localhost:8000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - postgresql-reviewer-network

  # Optional: Include backend service for complete setup
  # postgresql-reviewer-backend:
  #   image: your-backend-image:latest
  #   container_name: postgresql-reviewer-backend
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #   networks:
  #     - postgresql-reviewer-network

networks:
  postgresql-reviewer-network:
    driver: bridge
